# FOR DEVELOPMENT PURPOSES ONLY
name: biofood-dev

services:
  database:
    container_name: database
    image: postgres:13-alpine
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh:ro
      - ./dumps/${POSTGRES_DB_CUSTOMER}.sql:/docker-entrypoint-initdb.d/${POSTGRES_DB_CUSTOMER}.sql:ro
      - ./dumps/${POSTGRES_DB_MODEL}.sql:/docker-entrypoint-initdb.d/${POSTGRES_DB_MODEL}.sql:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB_CUSTOMER}, ${POSTGRES_DB_MODEL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build:
      context: ../backend
      target: dev
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ../backend/src
          target: /backend/src
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN_BASE}/${POSTGRES_DB_CUSTOMER}
      MINIO_USER_URL: ${MINIO_USER_URL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHMS: ${JWT_ALGORITHMS}

  s3:
    image: minio/minio
    env_file: .env
    command: |
      server --console-address ":9001" /data
    healthcheck:
      test: mc ready local
      interval: 60s
      start_period: 1s
      timeout: 600s
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  
  s3-setup:
    image: minio/mc
    env_file: .env
    depends_on:
      s3:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc alias set s3service http://s3:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb s3service/$$S3_BUCKET_NAME;
      /usr/bin/mc anonymous set download s3service/$$S3_BUCKET_NAME;
      /usr/bin/mc admin user svcacct add --access-key "$$S3_ACCESS_KEY" --secret-key "$$S3_SECRET_KEY" s3service $$MINIO_ROOT_USER;
      exit 0;
      "
